package com.example.cluedo_seii;

public enum GameState {
    START,
    PLAYERTURNBEGIN,
    PLAYERMOVEMENTDECISION,
    PLAYERMOVEMENT,
    PLAYERACCUSATION,
    PLAYERTURNEND,
    END,
    PASSIVE,
    WAITINGFORANSWER,
    SUSPECTED,
    RECEIVINGANSWER,
}
